metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:}'

metricbeat.modules:
- module: docker
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s